document.createElement('header');
document.createElement('hgroup');
document.createElement('nav');
document.createElement('menu');
document.createElement('main');
document.createElement('section');
document.createElement('article');
document.createElement('aside');
document.createElement('footer');